= Teletupsud
 
== Team members
 
* Kaur Kullamäe - electronics
* Kaarel Jalakas - mechanics
* Kaarel Kõomägi - programmer
* Sander Soodla  - programmer

== External sources
Github: https://github.com/ut-robotics/picr22-team-teletupsud +

== Blog
=== Week 1 +
*Bootcamp - 03.04.2022 - 04.04.2022* +
On Saturday, everybody learned the basics of PICR. That includes programming, mechanics and electronics. That includes soldering wires to the mainboard. Also, 3D designed a small motor holder so that you could connect the motor to the robot's body. Installing Ubuntu on the robot's computer and starting programming. +
Sunday: teams are formed. Randomly we picked up previous years teams "TLO Rock" box number 1.(8h+8h) +


=== Week 2 +
*05.09.2022* +
Everybody goes through the safety briefing, so we know how to operate in the lab safely.(60min) +
*08.09.2022* +
Programmers start setting up the computer. Because our computer is different from others, It uses mini HDMI for display out. The problem is that the lab has only one mini HDMI -> HDMI cable, and somebody also uses it. Another problem was that in the beginning, we decided not to do a fresh install of Ubuntu on the computer. But it started showing random memory errors, and we decided to reinstall it. That fixed our problem. (1.5h) +
Kaur and Kaarel decided to set up the test robot of the previous year's team. They ran into trouble when they connected everything up. Found that one of the ground wires was poorly soldered, they re-soldered it.(1.5h) +
Kaarel started taking dimensions of the robot's body to create the throwing mechanism(30min).

=== Week 3 + 
*12.09.2022* + 
Kaarel K and Sander started testing and programming. Trying to find the ball with the camera. Also trying to figure out the driving logic.(1.5h) +
Kaur started with PCB-s schematic design.(30min) +

*15.09.2022* +
Kaur completed all necessary wires and connector to connect the battery to the switch and to the robot itselt.(1.5h) +
Kaarel J is still designing the thrower mechanism and trying to get all the measurements right. (1,5h) +

*18.09.2022* +
Kaarel J finished designing the thrower mechanism and uploaded it for review. (3h) +

=== Week 4 + 
*21.09.2022* +
Kaarel J fixed some issues of the thrower mechanism which were pointed our in the review. (1,5h) +
 

