= Teletupsud
 
== Team members
 
* Kaur Kullamäe - electronics
* Kaarel Jalakas - mechanics
* Kaarel Kõomägi - programmer
* Sander Soodla  - programmer

== External sources
Github: https://github.com/ut-robotics/picr22-team-teletupsud +
Fusion360: https://a360.co/3sZL5JZ

== Blog
=== Week 1 +
*Bootcamp - 03.04.2022 - 04.04.2022* +
On Saturday, everybody learned the basics of PICR. That includes programming, mechanics and electronics. That includes soldering wires to the mainboard. Also, 3D designed a small motor holder so that you could connect the motor to the robot's body. Installing Ubuntu on the robot's computer and starting programming. +
Sunday: teams are formed. Randomly we picked up previous years teams "TLO Rock" box number 1.(8h+8h) +


=== Week 2 +
*05.09.2022* +
Everybody goes through the safety briefing, so we know how to operate in the lab safely.(60min) +
*08.09.2022* +
Programmers start setting up the computer. Because our computer is different from others, It uses mini HDMI for display out. The problem is that the lab has only one mini HDMI -> HDMI cable, and somebody also uses it. Another problem was that in the beginning, we decided not to do a fresh install of Ubuntu on the computer. But it started showing random memory errors, and we decided to reinstall it. That fixed our problem. (1.5h) +
Kaur and Kaarel decided to set up the test robot of the previous year's team. They ran into trouble when they connected everything up. Found that one of the ground wires was poorly soldered, they re-soldered it.(1.5h) +
Kaarel started taking dimensions of the robot's body to create the throwing mechanism(30min).

=== Week 3 + 
*12.09.2022* + 
Kaarel K and Sander started testing and programming. Trying to find the ball with the camera. Also trying to figure out the driving logic.(1.5h) +
Kaur started with PCB-s schematic design.(30min) +

*15.09.2022* +
Kaur completed all necessary wires and connector to connect the battery to the switch and to the robot itselt.(1.5h) +
Kaarel J is still designing the thrower mechanism and trying to get all the measurements right. (1,5h) +
Kaarel K and Sander - Omnimotion calculations (2h) +

*18.09.2022* +
Kaarel J finished designing the thrower mechanism and uploaded it for review. (3h) +

=== Week 4 + 
*21.09.2022* +
Kaarel J fixed some issues of the thrower mechanism which were pointed out in the review. (1,5h) +

*22.09.2022* +
Kaur debugged the voltage regulator not working. Issue was with faulty connectors and connections (30min) +
Programmers managed to make the robot move in one diretion. (1.5h)+
All members passed the introduction to battery managment. +

=== Week  5 +
*28.09.2022* +
 Kaarel J finished CAM model for milling. (1,5h) +
 
*29.09.2022* +
Kaarel J made some adjustments for CAM model and milled out thrower parts. (2h) +
Kaarel K and Sander got the robot to find and follow the ball. (2h) +

*30.09.2022* +
Kaarel J assembled thrower mechanics and attached to robot. (2h)+
Kaur basically finished the schematics of the robot(6h) +

=== Week 6 +
*03.10.2022* +
Kaarel J started designing omniwheels. (1h) +
Sander and Kaarel K fixed some issues with code based on feedback. (2h) +

*05.10.2022* +
Kaur designing the PCB. (2h) +

*06.10.2022* +
Kaur designing the PCB. (2h)+
Kaarel K and Sander started implementing state logic and fixed some ball tracking issues. (1,5h) +


=== Week 7 +
*10.10.2022* +
Sander and Kaarel K finished implementing states. (1h) +

*13.10.2022* +
Kaarel J working on omniwheel design. (2h) +
Kaur designing the PCB. (2h) +
Kaarel K and Sander improved centering of the ball, tried basic throwing. (2h) +

*14.10.2022*+
Kaur designing the PCB. (2h) +

*16.10.2022*+
Kaur finished the first version of PCB, sent it to the revision(2h) +

=== Week 8 +
*17.10.2022*+
Sander and Kaarel K tried a remote desktop solution, rotating around the ball (1h)+

*20.10.2022*
Sander and Kaarel K made a setup so we can run the code on our own laptop, fixed issues from pull request. (1,5h) +

*23.10.2022*+
Kaarel J working on omniwheels, minor tweaking and testing another design. (1,5h) +

=== Week 9 +
*24.10.2022*+
Sander and Kaarel K: basket thresholding, moved throwing logic, masked the motor in the camera view (2h) +
Kaur fixed some PCB desing bugs (2h) +

*26.10*2022* +
Kaarel J finished motormount design. (2,5h) +

*27.10.2022* +
Kaarel K and Sander: corrections while orbiting the ball, lining up with the basket and throwing (2h) +

=== Week 10 +
*31.10.2022* +
Kaur moved from CircuitMaker to Altium Designer and re-designed the PCB there(8h)+

*01.11.2022* +
Kaur finished the current PCB design and sent it to revision(4h)+

*03.11.2022* +
Kaarel made aluminium connectors for wheels (3h) +




